### PR TITLE
Remove APs

### PR DESCRIPTION
**Pull request by ataalik**
This PR removes atomic polygons. Not sure how it affects other PRs. Solves #97

### CODE REVIEW

**Comment by whirish** [comment]
> I believe we could remove 'List view for STVs, optimized for speed' (`get_stvs`) from views.py

We should probably do some profiling on this. As I remember it was originally added because it eliminated the overhead caused by subclassing ModelViewSet which was a suprisingly significant amount. But if request time is bearable now that we've gotten rid of the extra `INNER JOIN` it should be ok.

**Comment by MiklerGM** [comment]
> As I remember it was originally added because it eliminated the overhead caused by subclassing ModelViewSet which was a suprisingly significant amount. 

You right. Overhead can be explained by counting number of new objects that should be processed, and serialized
AFAIR we had 12k APs in total and circa 7k in use for each year, and 2k STV, so it's more like hundred thousands of objects (279146 stv territories).

PostgreSQL Request for aggregation everything together was executed in 0.5 seconds, and without using array_agg function 3.5 seconds.

**Comment by whirish** [comment]
Ah thanks. Definitely get rid of it then in this case. reverse() url queries in tests will have to be updated as well in this case

**Pull request merged**
