### PR TITLE
Remove CD.location null constraint and extend filtering

### LINKED ISSUE #51: Update the CD model to make the location optional
I support the corner implementation. I can update the CD model to make the location optional if the consensus is in support

_Originally posted by @whirish in https://github.com/chronhq/frontend/issues/31#issuecomment-461119097_

### PR DESCRIPTION
**Pull request by whirish**
Fixes #51. 
- [x] Makes location field optional
- [x] Allows filtering by CDs with a null location
- [x] Allows filtering by CDs matching a year

### CODE REVIEW

**Comment by whirish** [comment]
@MiklerGM I can exclude certain fields from serialization since they'll be returned in the MVT. 
As data begins to grow it may be worthwhile to look into a more permanent solution. GraphQL would solve this problem but has terrible Django support. We also discussed  https://github.com/chronoscio/backend/issues/56 on the old codebase.

**Comment by whirish** [comment]
I think I misread your earlier post. If you meant to return all items without a location I can add a query parameter to /cached-data, `?hasLocation=false` or something

**Comment by MiklerGM** [comment]
> I can add a query parameter to /cached-data, `?hasLocation=false` or something

That would be marvelous. Could you also add optional parameter for year?

**Comment by whirish** [comment]
@MiklerGM done. Query parameters are `?has_location=bool` and `?year=int`

**Pull request merged**
