### PR TITLE
Nest narration attached_events

### LINKED ISSUE #49: Narrative's attached_events as cache_table entities
If you want I can nest data to gave it return the cached table instances as JSON rather than just the IDs

_Originally posted by @whirish in https://github.com/chronhq/frontend/issues/10#issuecomment-459798047_

### PR DESCRIPTION
**Pull request by whirish**
Fixes #49. Opts for returning nested data in the `Narrations` serializer over the previous flat PKs.

```js
/** /api/narrations/1/ **/

// Before:
{
    "id": 1,
    "title": "Test Narration",
    // ...
    "settings": { 1 },
    "attached_events": [ 2, 3 ]
}

// Now:
{
    "id": 1,
    "title": "Test Narration",
    // ...
    "settings": {
        "id": 1,
        "bbox": {
            "type": "MultiPoint",
            "coordinates": [
                [
                    0.0,
                    0.0
                ],
                [
                    1.0,
                    1.0
                ]
            ]
        },
        "zoom_min": 1.0,
        "zoom_max": 12.0
    },
    "attached_events": [
        {
            "id": 2,
            "wikidata_id": 1,
            "location": {
                "type": "Point",
                "coordinates": [
                    0.0,
                    0.0
                ]
            },
            "date": "0001-01-01",
            "rank": 830700,
            "event_type": 178561
        },
        {
            "id": 3,
            "wikidata_id": 1,
            "location": {
                "type": "Point",
                "coordinates": [
                    0.0,
                    0.0
                ]
            },
            "date": "0001-01-01",
            "rank": 830700,
            "event_type": 178561
        }
    ]
}
```

### CODE REVIEW

**Comment by whirish** [comment]
I'm not sure why the tests aren't passing atm but I can reproduce it locally. I will have to look into this.

**Comment by amaurymartiny** [comment]
@whirish can we merge this? Do you still want to look into the travis error?

**Comment by MiklerGM** [comment]
That is too much info, I don't need info about narrative here
```
    {
        "id": 2,
        "order": 1,
        "title": "Napoleon against Britain",
        "description": "The conflict between France and Britain, continuously at war since 1793, tends always towards stalemate. The two nations are evenly matched but have very different strengths. Britain has a much smaller population (11 million compared to 27 million in France in 1801). This disadvantage is offset by Britain's wealth (from a more developed economy and extensive overseas trade) and by the British superiority at sea. In 1803 France has 23 ships of the line; Britain has 34 in service and another 77 in reserve.\nFor these reasons the British contribution to any war against France in continental Europe is largely limited to providing funds for allied armies. \nThe naval clash between Britain and France is a strange one - not so much a sea war as a coast war. It is the permanent concern of the British navy, commanding the seas, to harm France and her allies by preventing any merchant ships other than those of Britain from reaching continental ports. And it is the permanent concern of the French armies, commanding the land, to prevent British vessels entering those same ports. \nThird parties suffer as much as anyone from this form of economic warfare, particularly after Britain adopts the policy of seizing goods carried by the ships of neutral nations if they are destined for a harbour under blockade. \nIndignation at this British policy, heightened by diplomatic pressure from Napoleon, prompts Russia, Sweden and Denmark to form in December 1800 a League of Armed Neutrality. They declare the Baltic ports out of bounds to British ships. The embargo is strengthened when the Danes seize Hamburg, the main harbour for British trade with the German states.\nBritain responds by sending a naval fleet into the Baltic. The second-in-command is Nelson, who sails into shallow and well-defended waters in Copenhagen harbour. There is heavy fighting, during which the commander of the fleet flies the signal for Nelson to withdraw (this is the famous occasion when he puts the telescope to his blind eye). \nNelson destroys many of the ships in the harbour and damages the shore defences in this battle of Copenhagen (2 April 1801). His victory prompts the Danes to make peace in May. Sweden does so in the same month, and Russia follows suit in June.\nBy now, as after Campo Formio, Britain and France are the only two nations still at war. From the British point of view one affront still needs to be righted. In March 1801 a fleet is sent through the Mediterranean to help the Turks expel the French from Egypt. The French command in Cairo surrenders in June, followed by Alexandria in August. \nBoth sides are now exhausted. There have been tentative peace talks since February. Terms are agreed in October, putting an end to hostilities. The peace is signed in Amiens in March 1802.\nNapoleon's negotiators do well for France. All overseas territories taken by Britain in the past nine years (including several West Indian islands) are returned into French hands. Similarly Minorca reverts to Spain and the Cape colony in South Africa to Holland. But Britain keeps Sri Lanka (taken from the Dutch) and Trinidad (previously Spanish). Egypt is to be Turkish again. Malta (taken by Napoleon in 1798 and by Britain in 1800) is to be restored to the Knights of St John.",
        "date_label": "1800-1802",
        "map_datetime": "1800-01-01T00:00:00Z",
        "img": "http://www.historyworld.net/images/treasures/NelsonRigaudxaca300.jpg",
        "video": null,
        "narrative": {
            "id": 1,
            "author": "Bamber Gascoigne <http://www.historyworld.net>",
            "title": "Napoleonic Wars",
            "description": "History of the Napoleonic Wars",
            "tags": [
                "military",
                "conflict",
                "france",
                "europe",
                "revolution",
                "napoleon",
                "late modern era"
            ]
        },
        "settings": {
            "id": 2,
            "bbox": {
                "type": "MultiPoint",
                "coordinates": [
                    [
                        -15.751,
                        35.382
                    ],
                    [
                        51.046,
                        62.222
                    ]
                ]
            },
            "zoom_min": 1.0,
            "zoom_max": 15.0
        },
        "attached_events": [
            {
                "id": 613,
                "wikidata_id": 778800,
                "location": {
                    "type": "Point",
                    "coordinates": [
                        30.066666666,
                        31.316666666
                    ]
                },
                "date": "1799-07-25",
                "rank": 1452,
                "event_type": 178561
            },
            {
                "id": 909,
                "wikidata_id": 376154,
                "location": {
                    "type": "Point",
                    "coordinates": [
                        12.566666666,
                        55.666666666
                    ]
                },
                "date": "1807-01-01",
                "rank": 2646,
                "event_type": 178561
            },
            {
                "id": 1551,
                "wikidata_id": 432515,
                "location": {
                    "type": "Point",
                    "coordinates": [
                        -5.42916667,
                        36.13333333
                    ]
                },
                "date": "1801-07-06",
                "rank": 0,
                "event_type": 178561
            },
            {
                "id": 1602,
                "wikidata_id": 112183,
                "location": {
                    "type": "Point",
                    "coordinates": [
                        2.297777777,
                        49.891944444
                    ]
                },
                "date": "1802-03-25",
                "rank": 1394,
                "event_type": 131569
            }
        ]
    },
```

**Comment by whirish** [comment]
@amaurymartiny I'm still looking into it. POST requests fail currently so it's not a good idea to merge this yet.

**Comment by whirish** [comment]
Should be ready now. `GET` will return `attached_events` nested. `POST` takes `attached_events_ids`  which is an array of PKs pointing to existing CD instances and *does not take an `attached_events` property*.

**Pull request merged**
